kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: paswrd